= Rotaract Appointments

:badge_url: https://img.shields.io
:repo_path: rotaract/rotaract-appointments
:slug: rotaract-appointments

// General Badges
image:{badge_url}/badge/Open_Source-❤-orange[Open Source, link="https://opensource.org"]
image:{badge_url}/github/package-json/keywords/{repo_path}[GitHub package.json keywords, link="https://github.com/{repo_path}/blob/HEAD/package.json"]
image:{badge_url}/badge/code_style-WordPress-brightgreen[Code Style, link="https://make.wordpress.org/core/handbook/best-practices/coding-standards/"] +
// Status Badges
image:https://github.com/{repo_path}/actions/workflows/build.yml/badge.svg[Build Plugin ZIP, link="https://github.com/{repo_path}/actions/workflows/build.yml"]

https://wordpress.org/[WordPress] plugin for displaying appointments from https://mein.rotaract.de[mein Rotaract] using https://github.com/fullcalendar/fullcalendar[FullCalendar].

== Setup

In order to either setup the environment for development or install plugin manually follow these steps.

. Install Composer Dependencies (add command option `--no-dev` if you do not need development tools)
+
[source]
----
composer install
----
. Install Node Dependencies
+
[source]
----
npm install
----
. https://make.wordpress.org/cli/handbook/guides/installing/[Install WP-CLI]
. Build Translation Files
+
[source]
----
composer translate
----

== Installation

IMPORTANT: The plugin's latest version is already installed at https://hosting.rotaract.de[Rotaract Hosting].

. Download https://github.com/rotaract/rotaract-appointments/releases/latest/download/rotaract-appointments.zip[ZIP file containing latest version]
. Install Plugin in your WordPress instance

== Configuration

. Set parameter `ROTARACT_ELASTIC_HOST` in your `wp-config.php`
+
.snippet of `wp-config.php`
[source,php]
----
/**
 * Rotaract Params
 */
define( 'ROTARACT_ELASTIC_HOST', 'https://my-elastic-host.com:9200' );
----
. Navigate to setting page 'Rotaract' within the https://wordpress.org/support/article/administration-screens/[Administration Screen]
. Add at least one owner, select a color and save changes

== Usage

. Add the shortcode `[rotaract-appointments]` to a new or existing site that will insert the calendar
