= Rotaract Appointments

ifdef::env-github[]
:tip-caption: 💡
:note-caption: ℹ
:important-caption: ❗
:caution-caption: 🔥
:warning-caption: ⚠
endif::[]

:badge_url: https://img.shields.io
:repo_path: rotaract/rotaract-appointments
:slug: rotaract-appointments

// General Badges
image:{badge_url}/badge/Open_Source-❤-orange[Open Source, link="https://opensource.org"]
image:{badge_url}/github/package-json/keywords/{repo_path}[GitHub package.json keywords, link="https://github.com/{repo_path}/blob/HEAD/package.json"]
image:{badge_url}/badge/code_style-WordPress-brightgreen[Code Style, link="https://make.wordpress.org/core/handbook/best-practices/coding-standards/"] +
// Status Badges
image:https://github.com/{repo_path}/actions/workflows/build.yml/badge.svg[Build Plugin ZIP, link="https://github.com/{repo_path}/actions/workflows/build.yml"]

https://wordpress.org/[WordPress] plugin to display appointments of Rotaract Germany https://github.com/fullcalendar/fullcalendar[FullCalendar].

== ⭐ Features

* Display events of German Rotaract organisations in a calender
  (events must be marked as public in aurora)
* Multiple event owners / event sources
* Multiple views: list view, month view
* Customizable colors per event owner / event source
* Support of ICS subscription links
* Open-Source
* Internationalization

== 🔧 Installation

.Prerequisites
[NOTE]
--
* https://wordpress.com[WordPress] instance
* https://www.php.net[PHP] version 8.1 or higher (only use https://www.php.net/supported-versions.php[a supported version]
--

IMPORTANT: The plugin's latest version is already installed on https://hosting.rotaract.de[Rotaract Hosting].

. Download https://github.com/rotaract/rotaract-appointments/releases/latest/download/rotaract-appointments.zip[latest version packaged as ZIP file]
. https://wordpress.com/support/plugins/install-a-plugin/#install-a-plugin-with-a-zip-file[Install and activate plugin in WordPress]

== 🪛 Configuration

. Set Meilisearch parameters in your `wp-config.php`
+
.snippet of `wp-config.php`
[source,php]
----
define( 'ROTARACT_MEILISEARCH_URL', 'https://search.rotaract.de' );
define( 'ROTARACT_MEILISEARCH_API_KEY', '<your-meilisearch-api-key>' );
----
  * The Meilisearch API key is required to have `search` permission on indexes `Club`, `District`, `Mdio`, `Ressort`
. Set URL of event API
+
.snippet of `wp-config.php`
[source,php]
----
define( 'ROTARACT_AURORA_URL', 'https://aurora.rotaract.de' );
----
  * The URL of your WorePress site has to be registered in aurora to solve CORS issues
. Navigate to setting page 'Rotaract' within the https://wordpress.org/support/article/administration-screens/[Administration Screen]
. Add at least one owner, select a color and save changes

== 🪄 Usage

. Add the shortcode `[rotaract-appointments]` to a new or existing site that will insert the calendar.

== ⚖️ Legal Notices

Copyright (c) 2021-2024, Rotaract Deutschland

Licensed under European Union Public License 1.2 (EUPL-1.2).

_Rotary_, _Rotaract_ and _Interact_ are trademarks or registered trademarks of Rotary International and are used with the permission of Rotary International.
Other trademarks not owned by Rotary International are the property of their respective owners.
The license above does not grant any rights under trademark law and all such rights are reserved.
Modified versions must be renamed to avoid use of any Rotary International trademarks, including but not limited to _Rotary_, _Rotaract_ and _Interact_.

All Rotary, Rotaract and Interact logos and graphics are under copyright.
