name: Build Plugin ZIP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      php-version: latest
      extensions: imagick
      key: rotaract-appointments

    steps:
      - uses: actions/checkout@v6

      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ env.php-version }}
          extensions: ${{ env.extensions }}
          key: ${{ env.key }}

      - name: Cache extensions
        uses: actions/cache@v5
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.php-version }}
          extensions: ${{ env.extensions }}
          tools: wp

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Generate MO files for localization
        run: composer translate

      - name: Cleanup composer development packages and optimize autoloader
        run: composer install --no-dev --no-interaction --no-progress --optimize-autoloader --classmap-authoritative

      - name: Download JS vendor dependencies
        run: composer build

      - name: Upload Plugin
        uses: actions/upload-artifact@v7
        with:
          name: rotaract-appointments
          path: |
            ./*
            !.*
            !build
            !composer.json
            !composer.lock
            !devenv.*
            !phpcs.xml
            !tmp
